### ISSUE TITLE
Evaluate early migration to .NET 5

### ISSUE THREAD

**Issue by nxrighthere** [nxrighthere/UnrealCLR#13]
While .NET Core 3 provides straightforward embedding possibilities, the integration requires a lot of work with function pointers to make advanced blueprint nodes with direct data passing and events subscribing. The current workarounds are painful to work with and overcomplicated. Early migration to .NET 5 should be evaluated to solve this through C# 9.0 and new hostfxr functionality. The work on the framework API exposure can be continued mostly without problems.

**Comment by nxrighthere** [comment]
Related to https://github.com/nxrighthere/UnrealCLR/issues/14

**Comment by icavalheiro** [comment]
I believe the big question is "why not to". What are the biggest issues of moving to .net5 now? 
The only one I can think of is that .net5 is in preview mode and might not be installed in all developer's machines. But given that this project is also not production ready, I don't see that as being an issue.

**Comment by nxrighthere** [comment]
I ported the project to .NET 5 Preview 8 recently, but I encountered at least two critical issues: one with function pointers and another with dynamic assemblies loading. Can't merge it into the master in the current state.

**Comment by nxrighthere** [comment]
Related to https://github.com/nxrighthere/UnrealCLR/issues/31

**Comment by nxrighthere** [comment]
Postponed till .NET 5 release candidate.

**Comment by jmgomez** [comment]
Once it's migrated to RCx. What is the logical next step for getting it to work with mobile?

**Comment by nxrighthere** [comment]
@jmgomez The next step would be an investigation of Mono backend and its feature parity with CoreCLR. Other than that, Microsoft planned official support of Android in .NET 6. iOS requires AOT, its status is unknown at the moment.

**Comment by nxrighthere** [comment]
.NET 5 RC1 with C# 9.0 and F# 5.0 is ready to serve.
