### ISSUE TITLE
Could not load file or assembly 'System.Configuration.ConfigurationManager'

### ISSUE THREAD

**Issue by unknownRILL** [nxrighthere/UnrealCLR#154]
Hi,

I added a dependency .dll that was intended for .Net Framework 4.5 or later but when I try to call something from it I get this error in ue4: 

> LogUnrealCLR: Error: UnrealCLR::Module::Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
> File name: 'System.Configuration.ConfigurationManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

from googling around it seems like it has to do with compatibility issues between .net core and the .dll I'm using and System.Configuration not being compatible with core?

I tried using NuGet to install System.Configuration but that doesn't change the error and I also tried to NuGet https://www.nuget.org/packages/Microsoft.Windows.Compatibility
However that results in a similar error:

> 
> LogUnrealCLR: Error: UnrealCLR::Module::Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
> File name: 'System.Configuration.ConfigurationManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
>    at TheDLL.Net.Bluetooth.BluetoothFactoryConfig.get_KnownStacks()
>    at TheDLL.Net.Bluetooth.Factory.BluetoothFactory.GetStacks_inLock()
>    at TheDLL.Net.Bluetooth.Factory.BluetoothFactory.get_Factories()
>    at TheDLL.Net.Bluetooth.BluetoothRadio.get_AllRadios()
>    at TheDLL.Devices.Common.DeviceManager`1.get_IsBluetoothRadioEnabled()
>    at UnrealEngine.Tests.StaticMeshes.OnBeginPlay() in C:\Users\MyName\Downloads\UnrealCLR-1.29\Source\Managed\Tests\StaticMeshes.cs:line 39
>    at UnrealEngine.Tests.Main.OnWorldPostBegin() in C:\Users\MyName\Downloads\UnrealCLR-1.29\Source\Managed\Tests\Tests.cs:line 42
>    at UnrealEngine.Runtime.Core.ManagedCommand(Command command) in C:\Users\MyName\Downloads\UnrealCLR-1.29\Source\Managed\Runtime\Runtime.cs:line 150
> 

I even tried to 

` <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies> `

but I still get the same error.
I'm still rather new to .net and vs2019 if anyone could shed some light on how I can get UnrealCLR to be compatible with System.Configuration or if it is and I'm just not setting it up right please tell me how to properly set it up. If this is just something that's not going to be possible I'd also like to know since I do not have the source code for the .dll I'm trying to use so I can't change the parts that are using System.Configuration.

Thank you!

**Comment by nxrighthere** [comment]
Do you [publish](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish) a project or just build it?
