### ISSUE TITLE
Animation Blueprints public variables

### ISSUE THREAD

**Issue by Richmet706** [nxrighthere/UnrealCLR#16]
You are doing great work here. I was wondering if you could help me.
I have some animation blueprints from a C++ project.
Can you tell me how I might update public variables from the framework?
I noticed that this does not throw an error:
Blueprint animBlueprint = Blueprint.Load("Blueprint path");
MeshComponent.SetAnimationBlueprint(animBlueprint);
but I cannot cast the blueprint to an Actor:
Actor actor = new Actor("CAT_BP", animBlueprint);
as IsValidClass(Type) returns false.
The log shows:
Error: UnrealCLR::Module::Exception: System.InvalidOperationException: Operation is not valid due to the current state of the object.
Can you suggest a work-around? Thank you.

**Comment by nxrighthere** [comment]
You should use an appropriate type of blueprint class to create a C# actor or component class, otherwise, this exception will be thrown. What's the base class of those animation blueprints?

**Comment by nxrighthere** [comment]
I guess, you are trying to use `UAnimInstance`, like this one?

![animationblueprint](https://user-images.githubusercontent.com/8279330/89130198-621ba180-d51c-11ea-91f3-ee8f29c99cf4.png)

**Comment by Richmet706** [comment]
Thanks for replying so promptly.  Yes, I am trying to use an animation blueprint that has some public variables that control the animation selection, blend time, and speed. I thought I might be able to access the blueprint from the framework as I have for montages. I guess the best approach at this point would be to create a character blueprint that implements a common blueprint interface as the animation blueprint and pass the variables through the interface.

**Comment by nxrighthere** [comment]
@Richmet706 I've exposed properties for animation instances, see the example [here](https://github.com/nxrighthere/UnrealCLR/blob/master/Source/Managed/Tests/BlueprintsExtensibility.cs).

**Comment by Richmet706** [comment]
Thank you very much. I’ll look at this later today.

**Comment by Richmet706** [comment]
That change works beautifully. It certainly opens up many possibilities for
controlling animation directly from the framework.Thanks again.

**Comment by nxrighthere** [comment]
I'm glad to hear that, enjoy it!
