### ISSUE TITLE
Managed assemblies loading only from sub-folders

### ISSUE THREAD

**Issue by ScottKane** [nxrighthere/UnrealCLR#18]
I have just created a new BP project, installed UnrealCLR, created a .NET Core class library, copied C# entry point code from the manual, added reference to UnrealEngine.Framework, built class library to Managed folder with `dotnet build -o %Project%\Managed` and then ran in editor.

I'm not getting any of the on screen debug messages which I'm assuming means the entry point isn't working. The class library/framework dll's are in the Managed folder.

**Comment by nxrighthere** [comment]
Show me your code please.

**Comment by ScottKane** [comment]
```
using System;
using System.Drawing;
using UnrealEngine.Framework;

namespace Game
{
    public static class Main
    { // Indicates the main entry point for automatic loading by the plugin
        public static void OnWorldBegin() => Debug.AddOnScreenMessage(-1, 10.0f, Color.DeepPink, "Hello, Unreal Engine!");

        public static void OnWorldEnd() => Debug.AddOnScreenMessage(-1, 10.0f, Color.DeepPink, "See you soon, Unreal Engine!");

        public static void OnWorldPrePhysicsTick(float deltaTime) => Debug.AddOnScreenMessage(1, 10.0f, Color.DeepPink, "On pre physics tick invoked!");

        public static void OnWorldDuringPhysicsTick(float deltaTime) => Debug.AddOnScreenMessage(2, 10.0f, Color.DeepPink, "On during physics tick invoked!");

        public static void OnWorldPostPhysicsTick(float deltaTime) => Debug.AddOnScreenMessage(3, 10.0f, Color.DeepPink, "On post physics tick invoked!");

        public static void OnWorldPostUpdateTick(float deltaTime) => Debug.AddOnScreenMessage(4, 10.0f, Color.DeepPink, "On post update tick invoked!");
    }
}
```

**Comment by nxrighthere** [comment]
It works fine for me. The test project works for you? Which version of the plugin are you using?

**Comment by ScottKane** [comment]
I'm using the latest version of the plugin with UE4.25.3 and dotnet-sdk-3.1.401-win-x64 although during the installer I said no to the tests, will retry with the tests now

**Comment by nxrighthere** [comment]
If the test project doesn't work for you, then make sure that the plugin is properly initialized https://github.com/nxrighthere/UnrealCLR#running

**Comment by ScottKane** [comment]
It's working now, I think it's because I was building with `dotnet build -o %Project%\Managed\` but when I switched to `dotnet build -o %Project%\Managed\ClassLib` it's now working. I didn't realise output needed to be in a folder relative to the assembly name. Makes sense but could do with being a bit more clear in the docs

**Comment by nxrighthere** [comment]
It works from the root folder for me just fine without any sub-folders. It's most likely that the project is not published properly with that command. See https://github.com/nxrighthere/UnrealCLR#tests

**Comment by nxrighthere** [comment]
Nevermind, I found why this might happen, going to fix it quickly.

**Comment by ScottKane** [comment]
Awesome, also just been digging into the Tests and noticed that everything is static. What is the reason for this? Just wondering because in C++ you can for example do `ACharacterBase : ACharacter` whereas here if everything is static how do you do `CharacterBase : Character`? I ask because I was planning on using Dependency Injection which would require constructors.

**Comment by nxrighthere** [comment]
I did that in tests to quickly switch between them. If you have experience working with regular .NET applications where you have `Main()` entry point, then the principle here is the same. You have static [entry points](https://github.com/nxrighthere/UnrealCLR/blob/master/MANUAL.md#entry-point) from where you kickstart your logic and then organize your code the way you like. There's no intermediate scripts manager or stuff like that. You can use inheritance here too, see [this](https://github.com/nxrighthere/UnrealCLR/blob/master/Source/Managed/Tests/ObjectOrientedDesign.cs) test.

**Comment by ScottKane** [comment]
Ok yeah that makes sense, I was assuming I could do something like the following based on my understanding of the C++ workflow:

``` C#
public class PlayerCharacter : Character
{
    protected override void Tick()
    {
        base.Tick();
        Debug.Log(LogLevel.Display, "Tick");
    }
}
```

**Comment by nxrighthere** [comment]
Yea, the approach here is very different. The framework is not following idioms of the engine, so you can organize the execution flow and stuff the way you like with full control over it and keep it all managed. So to reproduce the same approach as in your example, you can create an intermediate scripts manager to execute logic using the object-oriented design or any other one.

**Comment by ScottKane** [comment]
Ok thanks for the info, will spend some time having fun with my own execution plan and see what I can come up with.
