### ISSUE TITLE
How should I be using the Actor.InputComponent?

### ISSUE THREAD

**Issue by ScottKane** [nxrighthere/UnrealCLR#19]
I have just been playing with the samples and I'm getting null ref exception when I call InputComponent.BindAction()

``` C#
public static class ObjectOrientedDesign
{
    private static Player _player;
    public static void OnBeginPlay()
    {
        Debug.AddOnScreenMessage(-1, 3.0f, Color.LightGreen, MethodBase.GetCurrentMethod().DeclaringType + " system started!");

        Engine.AddActionMapping("TestInput", Keys.W);
        _player = new Player(nameof(Player));
    }
}

public class Player : Actor
{
    public Player(string name = null) : base(name) => InputComponent.BindAction("TestInput", InputEvent.Repeat, InputTest);
    public void InputTest() => Debug.AddOnScreenMessage(-1, 0.1f, Color.Aqua, $"Input {World.RealTime}");
}
```

Is this not the correct usage?

**Comment by nxrighthere** [comment]
`InputTest` should be static in this case in order to pass it to the engine, otherwise, an exception will be thrown (this is covered in the API reference). See [this](https://github.com/nxrighthere/UnrealCLR/blob/c3d07283b3f5582b96b53dc1e76ae94e7a095cde/Source/Managed/Tests/DynamicsConsistency.cs#L44) test for action bindings.

**Comment by ScottKane** [comment]
I have tried making InputTest static and get the same exception

**Comment by ScottKane** [comment]
Not sure what is going on tbh, the following shows that the callback has a value and can be Invoked, BindAction() however still throws a null reference.

``` C#
public static class ObjectOrientedDesign
{
    private static Player _player;
    public static void OnBeginPlay()
    {
        Debug.AddOnScreenMessage(-1, 3.0f, Color.LightGreen, MethodBase.GetCurrentMethod().DeclaringType + " system started!");

        Engine.AddActionMapping("TestInput", Keys.W);
        _player = new Player(nameof(Player));
    }
}

public class Player : Actor
{
    public Player(string name = null) : base(name)
    {
        Debug.AddOnScreenMessage(-1, 3.0f, Color.Orange, name);
        var callback = new InputDelegate(TestInput);
        callback.Invoke(); // Works
        InputComponent.BindAction("TestInput", InputEvent.Pressed, callback); // Doesn't
    }

    private static void TestInput() => Debug.AddOnScreenMessage(-1, 2.1f, Color.Aqua, $"Input {World.RealTime}");
}
```

**Comment by nxrighthere** [comment]
First you need to add the component itself, you are trying to bind an action using a non-instantiated class, the null reference exception indicates that. Use a debugger to trace exceptions.

**Comment by nxrighthere** [comment]
You are trying to bind an action using a non-instantiated `InputComponent`, the exception indicates that. Use a debugger to properly trace exceptions.

**Comment by nxrighthere** [comment]
Since you are trying to use an `Actor` for your player class instead of a properly set up `PlayerController`, here's how the code should look like:
```csharp
namespace UnrealEngine.Tests {
	public static class ObjectOrientedDesign {
		private static Player _player;

		public static void OnBeginPlay() {
			Debug.AddOnScreenMessage(-1, 3.0f, Color.LightGreen, MethodBase.GetCurrentMethod().DeclaringType + " system started!");

			Engine.AddActionMapping("TestInput", Keys.W);
			_player = new Player(nameof(Player));
		}
	}

	public class Player : Actor {
		public Player(string name = null) : base(name) {
			this.SetEnableInput(World.GetFirstPlayerController(), true);
			this.InputComponent.BindAction("TestInput", InputEvent.Repeat, Player.InputTest);
		}

		public static void InputTest() => Debug.AddOnScreenMessage(-1, 0.1f, Color.Aqua, $"Input {World.RealTime}");
	}
}
```

**Comment by nxrighthere** [comment]
I'll expose the input enabling from code to make it easier to set up.

**Comment by ScottKane** [comment]
Ohhh I see, yeah that's my bad. I haven't gotten around to setting a debugger yet. Also is there a reason Character doesn't have a public constructor?

**Comment by nxrighthere** [comment]
Yea `Character` was not implemented and tested, I'll solve that today too.

**Comment by ScottKane** [comment]
Ok awesome, feel like maybe I shouldn't be raising issues for some of this but until discussions are up and running we don't really have a choice

**Comment by nxrighthere** [comment]
Nah, that helps me to make it better, so feel free to report issues, especially if you went to a dead end.

**Comment by ScottKane** [comment]
Sure, I have been working with Unity for a while so a bit out of the loop on how things are done in Unreal so excuse the rusty knowledge with which classes I should be using for some things. If things go to plan though I would be much happier in Unreal with UnrealCLR than Unity, they are stuck on full framework and haven't even gotten up to netstandard2.1 support yet, C# 8 isn't fully implemented (no default interface implementations) as well as no Nuget integration.

I know a lot of actual developers (not script kiddies) using Unity will likely move to Unreal when this plugin gets fully off the ground. Have to say I'm really impressed with the coverage you have achieved in such a short space of time.

**Comment by nxrighthere** [comment]
Thanks! We just need a better place for communication for sure (see my current plan [here](https://github.com/nxrighthere/UnrealCLR/issues/5#issuecomment-664068396)).

**Comment by ScottKane** [comment]
Yeah I had seen that, any idea when the feature will be moving out of beta or if they are likely to enable it for the beta on this repo?

**Comment by nxrighthere** [comment]
They told me that at least three proper contributors should be in the repository to enable this feature (technically, I'm the only one). I asked if this requirement is really necessary since this feature is needed to communicate with consumers primarily, and I haven't got a response from them yet.

**Comment by ScottKane** [comment]
Ahh that's a shame, you could always get a couple of community members to push a few of the proposed changes assuming they don't look into the commit history too much. But in an ideal world they will just let you have it regardless

**Comment by nxrighthere** [comment]
We'll figure this out. 👌🏻

**Comment by ScottKane** [comment]
Yeah no doubt, you could also just start a subreddit until discussions go live. On a side note I had a thought for future improvements, as you have a core runtime, you could in theory use Blazor as a way of creating UI from code which would be insanely cool

**Comment by nxrighthere** [comment]
I've exposed `Actor.SetEnableInput()` to push actors on to the stack of input handled by a `PlayerController` (see modified code example above in my comment).

The constructor for `Character` is provided, but functionality is in-progress.

**Comment by ScottKane** [comment]
Awesome, I will pull the new version and check it out
