### ISSUE TITLE
An exception occurs when using Assembly.LoadFile() to dynamically load Assembly

### ISSUE THREAD

**Issue by gedo4547** [nxrighthere/UnrealCLR#20]
I get an error when using the following code
  Assembly scriptAssembly = Assembly.LoadFile(scriptAssemblyFullName);
             Type[] types = scriptAssembly.GetTypes();

Error message:
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
System.IO.FileNotFoundException: Could not load file or assembly'test_lib'

I have ensured that the test_lib assembly is in the same directory as the assembly I need to load

Everything is normal when loading an Assembly without any dependencies, but if this Assembly depends on other assemblies, the above error will occur when using Assembly.GetTypes()

**Comment by nxrighthere** [comment]
I suspect why this could happen, will check.

**Comment by nxrighthere** [comment]
Do you encounter the same problem with just a regular .NET Core console application?

**Comment by gedo4547** [comment]
It works fine in .Net Core console applications without any problems

**Comment by nxrighthere** [comment]
Can you please provide a basic project for me?

**Comment by gedo4547** [comment]
Ok, I will upload the basic project on Monday

**Comment by gedo4547** [comment]
Hello, the basic project has been uploaded to my warehouse.
https://github.com/gedo4547/assembly_test
Due to the file size limitation of github, I compressed the package.
The entrance of the ue4 project is: tests
The dotnet project entry is: assembly_console_app

**Comment by nxrighthere** [comment]
I downloaded it, thanks. You can upload just managed code, that would be enough.

**Comment by nxrighthere** [comment]
It seems that CLR can't resolve dependencies properly with `Assembly.Load()` due to:

> For correct loading, all the dependant assemblies should be available from the host application path, GAC, or should be loaded manually in advance. 

If I use `Assembly.LoadFrom()` it works just fine.

I highly recommend `AssemblyLoadContext` in this case since it's a preferable approach in .NET Core to manage plugins. You can use [this](https://github.com/natemcmaster/DotNetCorePlugins) library that simplifies it a lot.

**Comment by gedo4547** [comment]
Thank you for your guidance, this should enable me to implement a very important module
