### ISSUE TITLE
InputComponent.BindAction() InputEvent.Repeat delayed

### ISSUE THREAD

**Issue by ScottKane** [nxrighthere/UnrealCLR#21]
The following results in the debug message being displayed as soon as the key is pressed:

``` C#
public static class ObjectOrientedDesign
{
    private static Player _player;
    public static void OnBeginPlay()
    {
        Debug.AddOnScreenMessage(-1, 3.0f, Color.LightGreen, MethodBase.GetCurrentMethod().DeclaringType + " system started!");

        Engine.AddActionMapping("TestInput", Keys.W);
        _player = new Player(nameof(Player));
    }

    public static void OnEndPlay() => Debug.ClearOnScreenMessages();
}

public class Player : Actor
{
    public Player(string name = null) : base(name)
    {
        Debug.AddOnScreenMessage(-1, 3.0f, Color.Orange, name);
        SetEnableInput(World.GetFirstPlayerController(), true);
        InputComponent.BindAction("TestInput", InputEvent.Pressed, TestInput);
    }

    public static void TestInput() => Debug.AddOnScreenMessage(-1, 0.1f, Color.Aqua, $"Input {World.RealTime}");
}
```

Changing InputEvent type to Repeat results in a noticeable delay of around 1-1.5 secs

``` C#
public Player(string name = null) : base(name)
{
    Debug.AddOnScreenMessage(-1, 3.0f, Color.Orange, name);
    SetEnableInput(World.GetFirstPlayerController(), true);
    InputComponent.BindAction("TestInput", InputEvent.Repeat, TestInput);
}
```

Should the input system be taking this long to trigger the event?

**Comment by nxrighthere** [comment]
I think this input behavior type is primarily designed for mouse actions since there's hard-coded protection against double-clicks with a slight delay, but I'm not sure. Use the [following](https://github.com/nxrighthere/UnrealCLR/blob/287eced0bbe5ee50ef262f357891ad7a07c7f9d9/Source/Managed/Tests/DynamicsConsistency.cs#L111) approach instead, it's a preferable way to handle key events.

**Comment by ScottKane** [comment]
Yeah I had looked at that example, I was trying to avoid it as it reduces the need to tick. Not sure I like that repeat works this way, as based on the action binding the event system should know that a double click would be expected behaviour in this case. It would also be bypassing the action bindings to use this approach so means you would have to roll your own binding system.

**Comment by ScottKane** [comment]
Based on the definition I would assume that Pressed/Released should fire once and Released should continuously fire until released

``` C#
/// <summary>Defines input behavior type</summary>
  public enum InputEvent
  {
    /// <summary>Key pressed</summary>
    Pressed,
    /// <summary>Key released</summary>
    Released,
    /// <summary>Key repeating</summary>
    Repeat,
    /// <summary>Key double clicked</summary>
    DoubleClick,
    /// <summary>Axis activated</summary>
    Axis,
  }
```

**Comment by ScottKane** [comment]
Also just looking through some of the Framework methods, would be nice if for anything that just takes a ref to return to as a void we could have a corresponding non void convenience method like so:

``` C#
/// <summary>
/// Retrieves the current size of the viewport and returns to a reference
/// </summary>
public static void GetViewportSize(ref Vector2 value) => getViewportSize(ref value);

/// <summary>
/// Retrieves the current size of the viewport
/// </summary>
public static Vector2 GetViewportSize()
{
    Vector2 value = default;
    getViewportSize(ref value);
    return value;
}

/// <summary>
/// Retrieves the current resolution of the screen and returns to a reference
/// </summary>
public static void GetScreenResolution(ref Vector2 value) => getScreenResolution(ref value);

/// <summary>
/// Retrieves the current resolution of the screen
/// </summary>
public static Vector2 GetScreenResolution()
{
    Vector2 value = default;
    getScreenResolution(ref value);
    return value;
}

/// <summary>
/// Retrieves the current location of the <a href="https://docs.unrealengine.com/en-US/Engine/LevelStreaming/WorldBrowser/index.html">world origin</a> to a reference
/// </summary>
public static void GetWorldOrigin(ref Vector3 value) => getWorldOrigin(ref value);

/// <summary>
/// Retrieves the current location of the <a href="https://docs.unrealengine.com/en-US/Engine/LevelStreaming/WorldBrowser/index.html">world origin</a>
/// </summary>
public static Vector3 GetWorldOrigin()
{
    Vector3 value = default;
    getWorldOrigin(ref value);
    return value;
}
```

**Comment by ScottKane** [comment]
I will create a PR and you can approve if you agree it's useful

**Comment by ScottKane** [comment]
See #22

**Comment by nxrighthere** [comment]
> I was trying to avoid it as it reduces the need to tick.

Yea, that makes sense. I'll take a look if there's something in the engine's API that can be used to solve this.

> Based on the definition I would assume that Pressed/Released should fire once and Released should continuously fire until released

It's not mentioned in their original documentation, unfortunately. I make assumptions based on the source code of the engine.

> Also just looking through some of the Framework methods, would be nice if for anything that just takes a ref to return to as a void we could have a corresponding non void convenience method like so:

Very good idea, I like it.

> I will create a PR and you can approve if you agree it's useful

I'll review it soon.

**Comment by nxrighthere** [comment]
[Here's](https://github.com/EpicGames/UnrealEngine/blob/45a3d87006bed4728355d290cca09167062a7ad8/Engine/Source/Runtime/Engine/Private/UserInterface/PlayerInput.cpp#L210) the source code for reference (you will need access to the private repository).

**Comment by ScottKane** [comment]
I have access to the repo already. 

``` C++
case IE_Repeat:
    KeyState.RawValueAccumulator.X = AmountDepressed;
    KeyState.EventAccumulator[Event].Add(++EventCount);
    if (KeyState.bDownPrevious == false)
    {
        // check for doubleclick
        // note, a tripleclick will currently count as a 2nd double click.
        const float WorldRealTimeSeconds = World->GetRealTimeSeconds();
        if ((WorldRealTimeSeconds - KeyState.LastUpDownTransitionTime) < GetDefault<UInputSettings>()->DoubleClickTime)
        {
            KeyState.EventAccumulator[IE_DoubleClick].Add(++EventCount);
        }

        // just went down
        KeyState.LastUpDownTransitionTime = WorldRealTimeSeconds;
    }
    break;
```

This seems strange to me, maybe there should be a bool for IsMouse which if false will bypass the double click check

**Comment by ScottKane** [comment]
Maybe something like this:

``` C++
bool UPlayerInput::InputKey(FKey Key, EInputEvent Event, float AmountDepressed, bool bGamepad, bool bMouse = true)
{
	// first event associated with this key, add it to the map
	FKeyState& KeyState = KeyStateMap.FindOrAdd(Key);
	UWorld* World = GetWorld();
	check(World);

	switch(Event)
	{
	case IE_Pressed:
	case IE_Repeat:
		KeyState.RawValueAccumulator.X = AmountDepressed;
		KeyState.EventAccumulator[Event].Add(++EventCount);
                if (bMouse == false)
                {
                    KeyState.EventAccumulator[IE_DoubleClick].Add(++EventCount);
                }
                else if (KeyState.bDownPrevious == false)
                { 
                    // check for doubleclick
                    // note, a tripleclick will currently count as a 2nd double click.
                    const float WorldRealTimeSeconds = World->GetRealTimeSeconds();
                    if ((WorldRealTimeSeconds - KeyState.LastUpDownTransitionTime) < GetDefault<UInputSettings>()->DoubleClickTime)
                    {
                        KeyState.EventAccumulator[IE_DoubleClick].Add(++EventCount);
                    }

                    // just went down
                    KeyState.LastUpDownTransitionTime = WorldRealTimeSeconds;
                }
		break;
```

**Comment by nxrighthere** [comment]
I would like to hear any information from them about how `EInputEvent::IE_Repeat` is supposed to be used, or just fill a bug report.

**Comment by ScottKane** [comment]
I have submitted a bug report with proposed improvements. To me it would make a lot of sense as it would allow a character to be controlled by input events without ticking while preserving compatibility
