### ISSUE TITLE
Engine.AddActionMapping/AddAxisMapping possible improvements

### ISSUE THREAD

**Issue by ScottKane** [nxrighthere/UnrealCLR#23]
Is there a limitation on the engine side preventing existing action/axis mappings from being remapped? Should there be `Enigine.RemoveActionMapping()`/`Engine.RemoveAxisMapping()`?

If they can exist then `Enigine.TryAddActionMapping()`/`Engine.TryAddAxisMapping()` should exist to create or update them, while `Add` remains only to add and throw an exception if the mapping exists.

**Comment by ScottKane** [comment]
Also the comment for `Engine.AddActionMapping()` is wrong

```
/// <summary>
/// Adds an engine defined axis mapping, cannot be remapped
/// </summary>
```

Should be `action` right?

**Comment by nxrighthere** [comment]
This is the engine's limitation, unfortunately, that they can't be remapped and should be unique.

Thanks for finding the typo, I'll fix it with the next commit.

**Comment by nxrighthere** [comment]
Probably [this](https://docs.unrealengine.com/en-US/API/Runtime/Engine/GameFramework/UPlayerInput/ForceRebuildingKeyMaps/index.html) method can be used to reset them entirely.

**Comment by ScottKane** [comment]
I guess as long you have empty mappings and configure them all through code everything can be changed. If this is the case though, how do they recommend updating bindings from a player's perspective at runtime?

**Comment by ScottKane** [comment]
Ahh okay so there's a clear all

**Comment by nxrighthere** [comment]
I think [`UPlayerInput::AddActionMapping`](https://docs.unrealengine.com/en-US/API/Runtime/Engine/GameFramework/UPlayerInput/AddActionMapping/index.html) and [`UPlayerInput::RemoveActionMapping`](https://docs.unrealengine.com/en-US/API/Runtime/Engine/GameFramework/UPlayerInput/RemoveActionMapping/index.html) should be used to set them per `UPlayerInput` instead of globally.

**Comment by nxrighthere** [comment]
Let me know if you need something else from [`UPlayerInput`](https://docs.unrealengine.com/en-US/API/Runtime/Engine/GameFramework/UPlayerInput/AddActionMapping/index.html).

**Comment by ScottKane** [comment]
Yeah that makes sense, in that case maybe add a note to these methods recommending using PlayerInput instead

**Comment by ScottKane** [comment]
Also you should check out docfx, you can run it against assemblies to generate a docs site, you can then use GitHub Actions to push it to a GitHub Pages site. would mean you don't need to manually maintain your docs

**Comment by nxrighthere** [comment]
Documentation is auto-generated with https://github.com/Doraku/DefaultDocumentation

**Comment by ScottKane** [comment]
Ahh ok, was just trying to save you doing it manually but if you already have generation in place there's probably not much point. It would however allow docs to be auto-generated from PR's without you having to clone it to generate on your machine

**Comment by nxrighthere** [comment]
Nah, it's not a problem. I do very little work by hand, mostly a bit of C++ and unit tests in C#, 80% of the workflow is automated (I spend a significant amount of time to implement a toolchain for that).

**Comment by nxrighthere** [comment]
I'll implement and test these functions tomorrow, going to bed now, stay tuned. 🛌🏻

**Comment by nxrighthere** [comment]
Resolved in https://github.com/nxrighthere/UnrealCLR/commit/10c4a238e890a408a303d856031f41fe0b2fd404
