### ISSUE TITLE
Change README to be multi-language compatible

### ISSUE THREAD

**Issue by ShalokShalom** [nxrighthere/UnrealCLR#236]
Hi there 👋🏼 

I read the Readme, and that you suggest in the section "Essentials" to use try/catch for error detection. 
In F#, we use the [option type](https://markjames.dev/2021-01-14-handling-errors-fsharp-with-option-types/) to deal with issues.

**Comment by nxrighthere** [comment]
Good point. Thanks!

**Comment by ShalokShalom** [comment]
FSharp does not encourage the usage of try .. with at all. As I showed you, option types are used. If you research that topic further, you will see that the rest of the text also does not apply. 

[FSharp does avoid exceptions](https://fsharpforfunandprofit.com/posts/exceptions/#the-error-code-based-approach) altogether, and casual, idiomatic fsharp code, even with millions of LOC, doesnt contain any line with try .. with in it. 

It is just there for compatibility reasons with C#.

**Comment by nxrighthere** [comment]
Thanks! I changed it to option types.

**Comment by nxrighthere** [comment]
I corrected it one more time. If you feel like you can make it more informative, please, submit a PR.
