### ISSUE TITLE
Install.cs does not seem to work.

### ISSUE THREAD

**Issue by tomheller2011** [nxrighthere/UnrealCLR#24]
Hi nxrighthere.
I stumbled onto UnrealCLR late last night, downloaded, tried the auto-install and it failed with message:
Compilation of the runtime was finished with an error!
I then followed the manual install procedure and eventually got everything loaded and running. Awesome!
Today, I saw there was an update about 10 hours ago.
It also appeared that the Install.cs got some change.
Alas, Install.cs did not work (same error message) and I cannot remember how I got it to compile and install manually.
I've tried for about 2 hours today. Can anyone help?
Thanks

**Comment by ScottKane** [comment]
Inside the `Install` directory in file explorer:
1. Type `cmd` into the url bar (where it says `C:\Path\To\UnrealCLR\Install`) - this will launch command prompt in this directory
2. Type `dotnet run` into the command prompt
3. Follow instructions to install to a Unreal Project

Can you confirm that this isn't working for you? I just tried on the latest code and it's working for me

**Comment by nxrighthere** [comment]
It works fine for me. Make sure that the working directory and the installation path are don't contain any special symbols.

**Comment by nxrighthere** [comment]
Also, if it still doesn't help, try to use a short path to the project.

**Comment by tomheller2011** [comment]
On my machine (Win10):
UnrealCLR lives at: C:\Users\Uzer\Documents\Visual Studio 2017\Projects\UnrealCLR (unzipped repository into this folder)
My UE4 project lives at: C:\Users\Uzer\Documents\Unreal Projects\Test425

I have used dotnet run executed from C:\Users\Uzer\Documents\Visual Studio 2017\Projects\UnrealCLR\Install and it does not work for me. Both paths do contain spaces... And yes, I do need a shorter path for UE4 projects. Thanks.
Anyway, after a few more tries and smoke breaks, this batch file works for me:

xcopy /E /Y "C:\Users\Uzer\Documents\Visual Studio 2017\Projects\UnrealCLR\Source\Native" "C:\Users\Uzer\Documents\Unreal Projects\Test425\Plugins\UnrealCLR"
cd "C:\Users\Uzer\Documents\Visual Studio 2017\Projects\UnrealCLR\Source\Managed\Runtime"
dotnet publish --configuration Release --framework netcoreapp3.1 --output "C:\Users\Uzer\Documents\Unreal Projects\Test425\Plugins\UnrealCLR/Managed"
dotnet publish "../Framework" --configuration Release --framework netcoreapp3.1

xcopy /E /Y "C:\Users\Uzer\Documents\Visual Studio 2017\Projects\UnrealCLR\Content" "C:\Users\Uzer\Documents\Unreal Projects\Test425\Content"
cd "C:\Users\Uzer\Documents\Visual Studio 2017\Projects\UnrealCLR\Source\Managed\Tests"
dotnet publish --configuration Release --framework netcoreapp3.1 --output "C:\Users\Uzer\Documents\Unreal Projects\Test425\Managed/Tests"

I did try modifying Install.cs - tried specifying the WorkingDirectory in StartInfo but nope. Will probably look some more.
Thanks for the replies, guys.

**Comment by nxrighthere** [comment]
Try to remove `<PackageReference Include="DefaultDocumentation" Version="0.6.11" PrivateAssets="all" />` from `UnrealEngine.Framework.csproj`.

**Comment by tomheller2011** [comment]
Same errmsg: Compilation of the runtime was finished with an error! (wish it would show the error but I didn't see a verbose option for dotnet/run and I'm extremely new to dotnet/core command line stuff - about 8 years of C# tho, desktop/utility apps.

**Comment by nxrighthere** [comment]
Navigate to `Source/Managed/Runtime` and run `dotnet publish --configuration Release --framework netcoreapp3.1 --output "%Project%/Plugins/UnrealCLR/Managed"` (replace `%Project%` with a path to the root directory of a project).

**Comment by nxrighthere** [comment]
Try to follow the [manual installation](https://github.com/nxrighthere/UnrealCLR#manual) process to get a more verbose error output.

**Comment by tomheller2011** [comment]
"Navigate to Source/Managed/Runtime and run dotnet publish --configuration Release --framework netcoreapp3.1 --output "%Project%/Plugins/UnrealCLR/Managed" (replace %Project% with a path to the root directory of a project)."
^^^This is exactly what my batch file does, and it works.^^^ I'm good for now.
Please don't spend any more time on this - save those brain cells for the important stuff :)

**Comment by nxrighthere** [comment]
That's actually strange, would be good to know what's going on there!

**Comment by nxrighthere** [comment]
The installation tool now displaying exit codes on errors, that should help.
