### ISSUE TITLE
SplineComponent API

### ISSUE THREAD

**Issue by Richmet706** [nxrighthere/UnrealCLR#29]
Hi. Hope you are doing well. Do you have any plans to expose spline components and controllers? Thank you.

**Comment by nxrighthere** [comment]
Sure, this API is in my to-do list. Any specific functions that you need with high priority?

**Comment by Richmet706** [comment]
I make use of the component for movement paths. Being able to get a reference to the component and make use of the "AtTime" functions would be great. Thank you.

**Comment by nxrighthere** [comment]
Will be exposed in the next update.

**Comment by Richmet706** [comment]
Thank you very much!

**Comment by nxrighthere** [comment]
@Richmet706 [SplineComponent](https://github.com/nxrighthere/UnrealCLR/blob/master/API/SplineComponent.md) is exposed in https://github.com/nxrighthere/UnrealCLR/commit/ef7dd4b79e41defaf00283d40e665bfcd3e174f6. This functionality is not tested.
