### ISSUE TITLE
Managed code is not running on Linux and Mac

### ISSUE THREAD

**Issue by Redageddon** [nxrighthere/UnrealCLR#30]
Running a project in ubuntu20.04 always leads to a *projectname* could not be compiled. Try rebuilding from source manually. error.

**Comment by nxrighthere** [comment]
Please, provide a full log.

**Comment by Redageddon** [comment]
[MyProject.log](https://github.com/nxrighthere/UnrealCLR/files/5158217/MyProject.log)

**Comment by Redageddon** [comment]
My steps were:
download UE4 like normal,
download your tool,
go to install and run `dotnet run`,
supplied it with the project path,
after it was finished i ran the project,
It asked me
![image](https://user-images.githubusercontent.com/53098956/91893383-e01cb680-ec48-11ea-8424-0b061df89644.png)
i clicked yes,
i then got 
![image](https://user-images.githubusercontent.com/53098956/91893434-f591e080-ec48-11ea-832e-b3dba126870e.png)

**Comment by nxrighthere** [comment]
What native compiler are you using?

**Comment by Redageddon** [comment]
Whatever ue4 downloads with

**Comment by Redageddon** [comment]
i believe its clang-9

**Comment by nxrighthere** [comment]
Thanks for the info. There's mismatching of data types I'll fix that.

**Comment by Redageddon** [comment]
Could you ping/message me when you think it is safe do download the source again?

**Comment by nxrighthere** [comment]
Sure thing.

**Comment by Redageddon** [comment]
I have a semi off topic question. Do you have a specific reason for having every class in 1 file? Would you accept a pull request if I split the classes into a file/folder structure?

**Comment by nxrighthere** [comment]
Amalgamated code is my personal preference.

**Comment by Redageddon** [comment]
Strange, but ok

**Comment by nxrighthere** [comment]
@rubiksmaster02 It should be fixed in the master branch now, but I can't check that at the moment. If the compilation still fails, then send me a full log, please.

**Comment by Redageddon** [comment]
OK, i will test and get back to you right now.

**Comment by Redageddon** [comment]
It failed again 
[MyProject.log](https://github.com/nxrighthere/UnrealCLR/files/5165773/MyProject.log)

**Comment by nxrighthere** [comment]
Interesting, there's even mismatching of Unreal's data types. I'll need to install it myself to fix that...

**Comment by Redageddon** [comment]
How long do you think this will take you?

**Comment by nxrighthere** [comment]
I'm working on it at the moment. It's not hard to fix those errors, but I need to set up a Linux environment for that.

**Comment by Redageddon** [comment]
Im curious, how do you know its a naming mismatch?

**Comment by nxrighthere** [comment]
There's mismatching of data types in your logs that are just platform-specific differences.

**Comment by Redageddon** [comment]
on my side the log have a whole bunch of wierd chars, I think my text editor isnt reading utf, so i cant read it easily

**Comment by Redageddon** [comment]
Yah i opened the log with rider and i can read it now. Ubuntus text editor just sucks

**Comment by nxrighthere** [comment]
@rubiksmaster02 It should be fixed now.

**Comment by Redageddon** [comment]
OK

**Comment by Redageddon** [comment]
if the Tests level is supposed to do anything it doesnt

**Comment by nxrighthere** [comment]
To make sure that it's initialized open the console window from `Window -> Developer Tools -> Output Log`, find `UnrealCLR` logs using the search input.

**Comment by Redageddon** [comment]
![image](https://user-images.githubusercontent.com/53098956/92166699-e4ce9f80-eded-11ea-85b6-e42ae8bc4081.png)

**Comment by nxrighthere** [comment]
Can you take a screenshot of the scene after entering the play mode? Because for me it works just fine.

**Comment by Redageddon** [comment]
It has also crashed on me twice so far.

**Comment by Redageddon** [comment]
![image](https://user-images.githubusercontent.com/53098956/92166925-5a3a7000-edee-11ea-9f30-51074c082b62.png)

**Comment by nxrighthere** [comment]
I need some info at this point:
- How did you install the engine? It was built from source or...?
- Current engine version
- Current  .NET Core SDK version

Also, can you share the output of the crash reporter?

**Comment by Redageddon** [comment]
Source, becuase that is the only way to get it on linux.
4.25.3
i have 3.1 and 5.0/beta

**Comment by Redageddon** [comment]
XD, the plot twist gets deeper

**Comment by nxrighthere** [comment]
This might be caused by how function pointers are used in the plugin. I'll need to wrap my head on how to diagnose and fix that. It might take the time up to migration to .NET 5.

**Comment by nxrighthere** [comment]
Okay, I'll try to fix that in the next couple of days. If that will not work, then I'm going to postpone this till migration to .NET 5.

**Comment by nxrighthere** [comment]
@rubiksmaster02 Give it a try now.

**Comment by Redageddon** [comment]
OK

**Comment by Redageddon** [comment]
It works now

**Comment by nxrighthere** [comment]
Awesome, thanks for the assistance.

**Comment by Redageddon** [comment]
Ill update you if i find anymore problems

**Comment by nxrighthere** [comment]
No problem.

**Comment by nxrighthere** [comment]
There's a minor issue with strings, it will be fixed soon.

**Comment by nxrighthere** [comment]
Should be fixed now.

**Comment by Redageddon** [comment]
What was the error?

**Comment by Redageddon** [comment]
everything was working on my end before the string fix

**Comment by nxrighthere** [comment]
It was a culture-specific issue, you could not notice it.

**Comment by Redageddon** [comment]
Ah
