### ISSUE TITLE
Blueprint Event Dispatchers

### ISSUE THREAD

**Issue by Eric900614** [nxrighthere/UnrealCLR#31]
Hi，I implemented an C# Http client to get data by API. I would like to pass the result to blueprint in UE. I know i could use actor variable, but it's not convenient. So i would like to know can i use blueprint event to dispatch data? Any idea or example will be very appreciated. 

Thanks 
Have  a nice day.

**Comment by nxrighthere** [comment]
A more direct data passing approach will be implemented with blueprint nodes generation.

**Comment by Eric900614** [comment]
thx. I know you will improve the workflow later. Looking forward to subsequent versions. Although, I think event system is important in any Game. We use it to decouple system modules.

Thanks, 
Have a nice day.

**Comment by nxrighthere** [comment]
Yes, .NET Core 3 lacks the right tools to solve that properly, unfortunately.

**Comment by Eric900614** [comment]
thx for your response and timly info.  Nice work for this plugin. Looking forward the .Net Version. 

Close this issue now. Have a nice day. 
Thanks

**Comment by nxrighthere** [comment]
Please, keep it open until resolved.

**Comment by nxrighthere** [comment]
@Eric900614 I would like to know more about your data. Is that a JSON string, a byte buffer, or something else?

**Comment by Eric900614** [comment]
@nxrighthere  Hi brother,  I use JSON string to pass data.  I get data by RESTful API and I would like to pass these JSON datas to blueprint actors. 

Have a nice day!
Thanks

**Comment by Eric900614** [comment]
The JSON data looks like as following:
`{
    "message":"success",
    "success":"true",
    "type":200,
    "data":[
        {
            "park_name":"ParkA",
            "using_space":190
        },
        {
            "park_name":"ParkB",
            "using_space":250
        },
        {
            "park_name":"ParkC",
            "using_space":300
        },
        {
            "park_name":"ParkD",
            "using_space":200
        }
    ]
}`

**Comment by nxrighthere** [comment]
Interesting, do you plan to use a blueprints plugin or custom nodes that can process JSON?

**Comment by Eric900614** [comment]
yep，we have a custom Blueprint plugin to process JSON data. The Process looks as following:

![image](https://user-images.githubusercontent.com/4131957/92846625-dc441d80-f41a-11ea-890f-916657ce02e0.png)

JSON string to useful blueprint struct

Thanks

**Comment by nxrighthere** [comment]
Resolved in https://github.com/nxrighthere/UnrealCLR/commit/7395da8d0c8c88b4f990ae09b56980950e2804b3. See example which invokes an event in the level blueprint: https://github.com/nxrighthere/UnrealCLR/blob/0fe35cbc9b27c2e39fe05a20dfb02aa4727ed98e/Source/Managed/Tests/BlueprintsExtensibility.cs#L35

**Comment by nxrighthere** [comment]
![x](https://user-images.githubusercontent.com/8279330/93323633-4cdda680-f82e-11ea-99a6-fe78d3c8a461.PNG)

**Comment by nxrighthere** [comment]
Added to manual https://github.com/nxrighthere/UnrealCLR/blob/master/MANUAL.md#data-passing

**Comment by Eric900614** [comment]
Nice work! Excellently. I will use it in my project. 

Thx again.
