### ISSUE TITLE
Level blueprint events executing earlier than world events

### ISSUE THREAD

**Issue by nxrighthere** [nxrighthere/UnrealCLR#32]
An attempt to solve this with tick prerequisites didn't work. An alternative approach should be investigated to preserve the order of execution.

**Comment by ScottKane** [comment]
You could use a stack containing the event order with an event dispatcher looping through the stack on event to propagate the events out in the correct order.

**Comment by nxrighthere** [comment]
The problem in this particular case is that events are based on the engine's tick groups using `FTickFunction`, so `ALevelScriptActor` events are ticking earlier than my custom world events. I tried to add my tick functions as prerequisites to `PrimaryActorTick` of `ALevelScriptActor`, but it doesn't work.

**Comment by ScottKane** [comment]
Strange that your approach didn't work, I would have thought that should do it, got any other ideas?

**Comment by nxrighthere** [comment]
I suspect that it's because my functions are registered and added as prerequisites after level events ticked already since I'm doing that using `OnWorldInitializedActors` callback. I need to find a way to register my tick functions and add them as prerequisites earlier than `ALevelScriptActor` ticked.

**Comment by nxrighthere** [comment]
Fixed in https://github.com/nxrighthere/UnrealCLR/commit/011ccf85d458c6e1db408ebe88186d85723b7482.
