### ISSUE TITLE
Verify blueprint classes matching with types of managed classes

### ISSUE THREAD

**Issue by nxrighthere** [nxrighthere/UnrealCLR#4]
At the moment, it's up to a programmer to ensure that blueprint classes have the same types as managed classes when blueprints dynamically loaded from managed code. There's no verification logic for this, therefore, loading of incompatible types of classes will lead to an error of the engine. An exception should be thrown instead.

**Comment by schotime** [comment]
Is it possible to populate the blueprint options by reflecting over the assemblies?

And I suppose something that comes up with this is the ability to instantiate a class on the begin event and then call methods from the instance rather than statics?

This probably ties in with #3 also.

**Comment by nxrighthere** [comment]
> Is it possible to populate the blueprint options by reflecting over the assemblies?

This will be possible with properties API which is currently work in progress and not available yet (see the [roadmap](https://github.com/users/nxrighthere/projects/5?fullscreen=true)).

> And I suppose something that comes up with this is the ability to instantiate a class on the begin event and then call methods from the instance rather than statics?

Since there's no management interlayer between your code and the runtime, it's up to you to instantiate classes and store them the way you like. Same as with a regular .NET application where you start from `static void Main()` entry point, you have to kickstart the logic and data from events of the engine.

Yes, #3 might introduce a management interlayer for this, but the final design is still not finished yet.

**Comment by schotime** [comment]
yeh, cool, wasn't sure what the properties API meant. 

I just meant that an alternative would be to return a pointer to the object created (from a LoadAssemblyObject() function) and then be able to call methods on that instance.

**Comment by nxrighthere** [comment]
@schotime Properties for actors and components are now exposed. See the example  [here](https://github.com/nxrighthere/UnrealCLR/blob/master/Source/Managed/Tests/BlueprintsExtensibility.cs).

**Comment by schotime** [comment]
Awesome!
So does the properties API control the menu items that appear in 
![image](https://user-images.githubusercontent.com/202923/85054466-6ba4b080-b1df-11ea-8749-eebc11df2498.png)
??

**Comment by nxrighthere** [comment]
> blueprint options

By blueprint options, you mean blueprint nodes? Nope, blueprint nodes should be defined and implemented in C++. The plugin provides two nodes: one is for loading managed assemblies and another for invoking functions.

What is exposed now is access to this:
![x](https://user-images.githubusercontent.com/8279330/85061641-9d5a4f00-b1c0-11ea-91c4-e08d6a64d257.PNG)

See the blueprints extensibility test with actor and scene component blueprints to get an idea of how to pass data from managed code to the engine objects.
