### ISSUE TITLE
Custom components by inheriting ActorComponent

### ISSUE THREAD

**Issue by atomicstan** [nxrighthere/UnrealCLR#50]
I've basically started with unreal engine thanks to your plugin. Creating custom components by inheriting `ActorComponent` seems like the way of doing things if I don't want to implement everything in a custom `Actor`. However it's not possible to inherit `ActorComponent` due to its constructor protection levels:
https://github.com/nxrighthere/UnrealCLR/blob/7372bdceef77818c199ee1a8fc606b3db871fd40/Source/Managed/Framework/Framework.cs#L7488
https://github.com/nxrighthere/UnrealCLR/blob/7372bdceef77818c199ee1a8fc606b3db871fd40/Source/Managed/Framework/Framework.cs#L7490

If I understand correctly sounds like the right constructor hasn't been implemented/exposed yet.

If it's not a rocket science I wouldn't mind to do that on my own, but I would appreciate some pointers.

**Comment by nxrighthere** [comment]
You are trying to create a class that derived from a non-insatiable abstract class. Use classes that are represented in the world and derived from `ActorComponent` such as `SceneComponent`.

I've added a [missed keyword](https://github.com/nxrighthere/UnrealCLR/commit/1fa9023d3844078c7c6f427ccccacfc22cdd0502) to the `ActorComponent` class, so it should make thing a bit more clear.
