### ISSUE TITLE
Strings encoding for non-English characters

### ISSUE THREAD

**Issue by Eric900614** [nxrighthere/UnrealCLR#52]
I can read a text file, but a few Chinese characters appear as black squares, or gibberish. 

Test Code:
![image](https://user-images.githubusercontent.com/4131957/96549144-a9c2f580-12e1-11eb-9ca5-4e6245b59f44.png)

Result:
![image](https://user-images.githubusercontent.com/4131957/96549161-b21b3080-12e1-11eb-97cd-1a10506a2dbd.png)

Could u add following code to translate before return in your source code?

![image](https://user-images.githubusercontent.com/4131957/96549290-e131a200-12e1-11eb-8560-c7ae85aba4e1.png)

**Comment by nxrighthere** [comment]
Have you tested it? Does UTF-8 solve this issue on your end?

**Comment by Eric900614** [comment]
Hi, I read the csv file by Encoding UTF-8. No working. 

![image](https://user-images.githubusercontent.com/4131957/96559729-00373080-12f0-11eb-9f4c-860b744c31ad.png)

This is my csv file. 
![image](https://user-images.githubusercontent.com/4131957/96559854-2361e000-12f0-11eb-8115-0d5fd817e04a.png)

Debug shows error as following:
![image](https://user-images.githubusercontent.com/4131957/96560067-60c66d80-12f0-11eb-86bb-6f02ee76f813.png)

Any advice will be appreciated. Thanks

**Comment by nxrighthere** [comment]
I mean have you tried to use `UTF8_TO_TCHAR` instead of `ANSI_TO_TCHAR` changing the source code of the plugin?

**Comment by Eric900614** [comment]
😄  Not yet. Just a suggestion

**Comment by nxrighthere** [comment]
This change also requires to explicitly re-encode managed strings to UTF-8, I think it should work.

**Comment by Eric900614** [comment]
I tried to use `UTF8_TO_TCHAR` instead of `ANSI_TO_TCHAR`  in source code, but not work.

![image](https://user-images.githubusercontent.com/4131957/96664037-84d38e80-1384-11eb-8b15-1156f057fb26.png)

Result：
![image](https://user-images.githubusercontent.com/4131957/96664060-9026ba00-1384-11eb-8400-b3000cf8806c.png)

**Comment by nxrighthere** [comment]
As I mentioned in my previous comment, you have to re-encode managed strings to UTF-8 as well, by default they marshalled as ANSI strings.

**Comment by nxrighthere** [comment]
@Eric900614 When strings re-encoded to UTF-8 at both ends it works well: 
![x](https://user-images.githubusercontent.com/8279330/96833608-2e388400-145a-11eb-81f3-a5f78c29dcaa.png)

I'll fix that across the codebase.

**Comment by Eric900614** [comment]
Good news，thx

**Comment by nxrighthere** [comment]
Solving this issue across the codebase is more problematic than I thought. I can easily solve encoding in functions like logging and debugging, but, for example, when it comes to actor names obtained from the native side, the runtime doesn't handle encoding properly for some reason. I need to fill a bug report about it.

Would it be helpful to fix encoding only in one direction from managed to native side, for now?

**Comment by beep2bleep** [comment]
Yes I think it would be helpful to fix the one direction we can.  I'm sure Epic will find they need to fix the other direction anyway some point soon since I assume this impacts Blueprints trying to get stuff from Native. Which I could see a problem for anyone doing something as mundane as displaying a leaderboard with Asian names.

________________________________

**Comment by nxrighthere** [comment]
Partially solved in https://github.com/nxrighthere/UnrealCLR/commit/ad5f263657fee5426bacc4ff25a3b8d52cde48cc for `Assert.Message()`, `Debug.Log()`, `Debug.Exception()`, `Debug.AddOnScreenMessage()`, `Actor.Invoke()`, `ActorComponent.Invoke()`, and `AnimationInstance.Invoke()`.

**Comment by SebbiUltimate** [comment]
Could you please add UTF-8 Support to GetString here?
https://github.com/nxrighthere/UnrealCLR/blob/8a43fd1fa14d5cb0f5bf3a0e8106c1da71a7eb0a/Source/Native/Source/UnrealCLR/Private/UnrealCLRFramework.cpp#L674

**Comment by nxrighthere** [comment]
Fixed across the codebase in https://github.com/nxrighthere/UnrealCLR/commit/65624ec6bbce7c8e8b355d01ecd0fcb6165abbf2.
