### ISSUE TITLE
Managed code is not executing if the level actor doesn't persist in the world

### ISSUE THREAD

**Issue by ScottKane** [nxrighthere/UnrealCLR#54]
1. Create Unreal BP project.
2. Install UnrealCLR.
3. Create .NET 5.0 RC2 project referencing UnrealCLR framework dll.
4. Add the following to the project:
``` c#
using System;
using System.Drawing;
using UnrealEngine.Framework;

namespace Game
{
	public static class Main
	{
		public static void OnWorldBegin() => Debug.AddOnScreenMessage(-1, 10.0f, Color.DeepPink, "Hello, Unreal Engine!");

		public static void OnWorldPostBegin() => Debug.AddOnScreenMessage(-1, 10.0f, Color.DeepPink, "How's it going?");

		public static void OnWorldEnd() => Debug.AddOnScreenMessage(-1, 10.0f, Color.DeepPink, "See you soon, Unreal Engine!");

		public static void OnWorldPrePhysicsTick(float deltaTime) => Debug.AddOnScreenMessage(1, 10.0f, Color.DeepPink, "On pre physics tick invoked!");

		public static void OnWorldDuringPhysicsTick(float deltaTime) => Debug.AddOnScreenMessage(2, 10.0f, Color.DeepPink, "On during physics tick invoked!");

		public static void OnWorldPostPhysicsTick(float deltaTime) => Debug.AddOnScreenMessage(3, 10.0f, Color.DeepPink, "On post physics tick invoked!");

		public static void OnWorldPostUpdateTick(float deltaTime) => Debug.AddOnScreenMessage(4, 10.0f, Color.DeepPink, "On post update tick invoked!");
	}
}
```
5. Publish to Unreal project Managed directory.
6. In Unreal File -> New Level
7. Play

Expected: Debug messages being displayed on screen.
Actual: Nothing

Haven't worked with the plugin in a while as I've been busy with my day job but this should be working right?

If I empty the Managed folder, publish the Tests and copy the Content folder and load the Tests level, the tests work. So not sure why my simple example doesn't run. Any ideas?

**Comment by nxrighthere** [comment]
What engine version are you running?

**Comment by ScottKane** [comment]
4.25.4

**Comment by nxrighthere** [comment]
I just updated Unreal and encountered the same thing, something weird with the engine.

**Comment by ScottKane** [comment]
Ahh ok so it's not just me

**Comment by nxrighthere** [comment]
It should be fixed now. Clone the repository and re-install the plugin. If you still have some issues, please, clean up the following directories of the project after making a backup:
```cmd
rmdir /s /q Binaries
rmdir /s /q Build
rmdir /s /q Intermediate\Build
rmdir /s /q Intermediate\Staging
rmdir /s /q Saved\Backup
rmdir /s /q Saved\Config\CrashReportClient
rmdir /s /q Saved\Cooked
rmdir /s /q Saved\Crashes
rmdir /s /q Saved\EditorCooked
rmdir /s /q Saved\Logs
rmdir /s /q Saved\StagedBuilds
rmdir /s /q Saved\Temp
```

**Comment by ScottKane** [comment]
Plugin is now working as expected, thanks

**Comment by ScottKane** [comment]
Although when I try to use a Nuget package I'm getting exceptions:

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Reactive, Version=5.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'. The system cannot find the file specified.
File name: 'System.Reactive, Version=5.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'
```

System.Reactive is a Nuget dependency of the project and is inside the Managed/Project.deps.json, the dll doesn't appear to be copied to the Manged directory though

**Comment by nxrighthere** [comment]
I believe it's not related to the plugin. It's most likely a problem with the NuGet package itself or .NET toolchain. Make sure that your project is published properly.

**Comment by ScottKane** [comment]
adding `<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>` to a property group works

**Comment by ScottKane** [comment]
`World.GetFirstPlayerController()` is returning null when testing some code I was writing a while ago. Is there not a default PlayerController?

**Comment by nxrighthere** [comment]
At which world event are you trying to obtain the controller?

**Comment by ScottKane** [comment]
OnWorldBegin

**Comment by nxrighthere** [comment]
This world event is executed before the default actors of a [GameMode](https://docs.unrealengine.com/en-US/Gameplay/Framework/GameMode/index.html) are spawned, see the [manual](https://github.com/nxrighthere/UnrealCLR/blob/master/MANUAL.md#world-events). Use `OnWorldPostBegin()` instead.

**Comment by ScottKane** [comment]
Ok cool, I don't think `OnWorldPostBegin()` was implemented last time I worked with the plugin, I notice there are a few more world events now

**Comment by nxrighthere** [comment]
Yes, I redesigned them a bit for upcoming API in future versions.

**Comment by ScottKane** [comment]
Ok makes sense. I now just need to figure out why my movement isn't working relative to the camera.

I don't think I will be able to just have one move method tbh, I will most likely need a move forward and a move right, however the movement I'm getting is a bit off:

``` c#
public class Player : Character
{
    private readonly PlayerController _controller;

    public Player() : base($"{nameof(Player)}1")
    {
        _controller = World.GetFirstPlayerController();
        _controller.Possess(this);

        new StaticMeshComponent(this).SetStaticMesh(StaticMesh.Cube);
        var springArmComponent = new SpringArmComponent(this);
        new CameraComponent(this).AttachToComponent(springArmComponent, AttachmentTransformRule.KeepRelativeTransform);

        MapPlayerInput(_controller.GetPlayerInput());
        BindPlayerInput(_controller.InputComponent);
    }

    public void Move(float value)
    {
        if (Math.Abs(value) > 0) Debug.AddOnScreenMessage(-1, 0.1f, Color.LimeGreen, $"Moving {value}");
        var rotation = _controller.GetControlRotation();
        var direction = new Vector3 { X = rotation.X, Y = rotation.Y, Z = rotation.Z };
        AddMovementInput(direction, value);
    }

    public void LookHorizontal(float value)
    {
        if (Math.Abs(value) > 0) Debug.AddOnScreenMessage(-1, 0.1f, Color.LimeGreen, $"Looking Horizontal {value}");
        AddControllerYawInput(value);
    }

    public void LookVertical(float value)
    {
        if (Math.Abs(value) > 0) Debug.AddOnScreenMessage(-1, 0.1f, Color.LimeGreen, $"Looking Vertical {value}");
        AddControllerPitchInput(value);
    }

    public void MapPlayerInput(PlayerInput input)
    {
        input.AddActionMapping("Jump", Keys.SpaceBar);

        input.AddAxisMapping("MoveForward", Keys.W);
        input.AddAxisMapping("MoveForward", Keys.S, -1f);

        input.AddAxisMapping("MoveRight", Keys.D);
        input.AddAxisMapping("MoveRight", Keys.A, -1f);

        input.AddAxisMapping("LookHorizontal", Keys.MouseX);
        input.AddAxisMapping("LookVertical", Keys.MouseY);
    }

    public void BindPlayerInput(InputComponent input)
    {
        input.BindAction("Jump", InputEvent.Pressed, Jump);
        input.BindAction("Jump", InputEvent.Released, StopJumping);

        input.BindAxis("MoveForward", Move);
        input.BindAxis("MoveRight", Move);

        input.BindAxis("LookHorizontal", LookHorizontal);
        input.BindAxis("LookVertical", LookVertical);
    }
}
```

I think this is because the returned Quaternion from `_controller.GetControlRotation()` is in world space and not local. Any ideas on how to achieve this?
