### ISSUE TITLE
Epic MegaGrants

### ISSUE THREAD

**Issue by rmerkushin** [nxrighthere/UnrealCLR#7]
Hi man! I think you should apply on [Epic MegaGrants](https://www.unrealengine.com/en-US/megagrants)!

P.S.: Anyway, thanks for your work!

**Comment by nxrighthere** [comment]
Hey, thanks! The project was submitted, and Epic is in touch with me. 👌

**Comment by jimboc1** [comment]
> Hey, thanks! The project was submitted, and Epic is in touch with me. 👌

First thing I said to @Schotime when he introduced UnrealCLR to me was "MegaGrant written all over it - so much c# talent out there resorting to Unity."

**Comment by nxrighthere** [comment]
@jimboc1 Thanks! We are moving forward. ❤️
