### ISSUE TITLE
The plugin doesn't compile with 4.26.0

### ISSUE THREAD

**Issue by ClaymoreStudio** [nxrighthere/UnrealCLR#91]
New blank blueprints project: "Project' could not be compiled. Try rebuilding from source manually."

Version 4.26.0.

**Comment by ClaymoreStudio** [comment]
I fixed this now, just went through the project in Visual Studio and recompiled. It is inconvenient but it works.

**Comment by nxrighthere** [comment]
@ClaymoreStudio Can you send me logs of building process before and after success, please?

**Comment by ClaymoreStudio** [comment]
How do i get those?

**Comment by ClaymoreStudio** [comment]
How do i get those?

**Comment by nxrighthere** [comment]
It should be stored in the `Saved` folders of the project.

**Comment by nxrighthere** [comment]
It should be stored in the `Saved` folder of the project.

**Comment by ClaymoreStudio** [comment]
[UnrealVersionSelector-2021.01.17-12.47.15.log](https://github.com/nxrighthere/UnrealCLR/files/5826770/UnrealVersionSelector-2021.01.17-12.47.15.log)
[UnrealVersionSelector-2021.01.17-13.19.10.log](https://github.com/nxrighthere/UnrealCLR/files/5826771/UnrealVersionSelector-2021.01.17-13.19.10.log)
[UnrealVersionSelector-2021.01.17-13.21.01.log](https://github.com/nxrighthere/UnrealCLR/files/5826772/UnrealVersionSelector-2021.01.17-13.21.01.log)
[KTAG.log](https://github.com/nxrighthere/UnrealCLR/files/5826773/KTAG.log)
[KTAG-backup-2021.01.17-12.47.02.log](https://github.com/nxrighthere/UnrealCLR/files/5826774/KTAG-backup-2021.01.17-12.47.02.log)
These are all the logs i could find in that folder
